import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/ui/Navbar';
import Footer from './components/ui/Footer';
import ContextProvider from './context-provider/contextProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'FIT-LOG-SITE',
  description: 'Generated by MD SHAHIDUL',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ContextProvider>
          <div className="h-[80px]">
            <Navbar></Navbar>
          </div>
          <div>{children}</div>
          <div>
            <Footer></Footer>
          </div>
        </ContextProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
